###############################
### MACHINE SPECIFIC CONFIG ###
###############################

# Provided below is an example config sufficient for basic functionality

exec-once = swaybg -i ~/.config/hypr/wallpapers/ball.png -m fill

monitor = , preferred, auto, auto

render {
   	direct_scanout = true
}
