$font = System-ui

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = $INPUT_FIELD_X, $INPUT_FIELD_Y 
    outline_thickness = $INPUT_FIELD_BEZEL_WIDTH
    fade_on_empty = false
    rounding = 999
        
    inner_color = rgba(0, 0, 0, 0.7)
    outer_color = rgba(0, 0, 0, 0.2)
    check_color = rgba(255, 255, 255, 0.2)
    fail_color = rgba(255, 255, 255, 0.2)

    font_family = $font
    font_color = rgb(140, 140, 140)
    placeholder_text = Password

    dots_size = 0.25
    dots_spacing = 0.25

    hide_input = false

    position = 0, -20
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = $TIME
    font_size = $TIME_SIZE
    font_family = $font Bold
    color = rgba(255, 255, 255, 0.7)

    position = 0, 0
    halign = center
    valign = top
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = $DATE_SIZE
    font_family = $font Bold
    color = rgba(255, 255, 255, 0.5)

    position = 0, $DATE_Y
    halign = center
    valign = top
}

# User icon
label {
    monitor =
    text = 
    font_size = $USER_ICON_SIZE
    color = rgba(255, 255, 255, 0.7)

    position = 0, $USER_ICON_Y
    halign = center
    valign = center
}

# User
label {
    monitor =
    text = $USER
    font_size = $USER_LABEL_SIZE
    color = rgba(255, 255, 255, 0.7)

    position = 0, $USER_LABEL_Y
    halign = center
    valign = center
}

# Battery
label {
    monitor =
    text = cmd[update:60000] ~/.config/hypr/scripts/hyprlock_battery_text.sh
    font_size = 23
    font_family = $font Bold
    color = rgba(255, 255, 255, 1)

    position = 20, -25
    halign = left
    valign = top
}
