#######################
### HYPRLAND CONFIG ###
#######################

source = ~/.config/hypr/core.conf
source = ~/.config/hypr/look_and_feel.conf
source = ~/.config/hypr/surfaces.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/host.conf
