######################
### INPUT SETTINGS ###
######################

input {
    kb_layout = pl

    sensitivity = -0.2

    follow_mouse = 1

    touchpad {
        scroll_factor = 0.15
        natural_scroll = true
        clickfinger_behavior = true
        drag_3fg = 2
    }
}

# Scrolling factors

windowrule = scroll_touchpad 1, match:class (foot)
windowrule = scroll_touchpad 0.5, match:class (org.gnome.Nautilus)
windowrule = scroll_touchpad 0.3, match:class (code)

