######################
### INPUT SETTINGS ###
######################

input {
    kb_layout = pl
    repeat_delay = 200
    repeat_rate = 30

    sensitivity = -0.2

    follow_mouse = 1

    touchpad {
        scroll_factor = 0.15
        natural_scroll = true
        clickfinger_behavior = true
        drag_3fg = 2
    }
}

binds:scroll_event_delay = 0

# Scrolling factors

windowrule = scroll_touchpad 1, match:class (kitty)
windowrule = scroll_touchpad 1, match:class (neovim)
windowrule = scroll_touchpad 1, match:class (unicode-input)
windowrule = scroll_touchpad 0.5, match:class (org.gnome.Nautilus)
windowrule = scroll_touchpad 0.3, match:class (code)
windowrule = scroll_touchpad 0.1, match:class (com.saivert.pwvucontrol)
