#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 1

    col.active_border = rgba(ffffff38) rgba(ffffff1a) 90deg
    col.inactive_border = rgba(ffffff1a)

    resize_on_border = true

    allow_tearing = true

    layout = dwindle
}

decoration {
    rounding = 20
    rounding_power = 2

    active_opacity = 1
    inactive_opacity = 1

    shadow {
        enabled = true
        range = 10
        render_power = 1
        color = rgba(00000077)
        color_inactive = rgba(00000000)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
    }
}

animations {
    enabled = yes, please :)

    bezier = linear,          0.00, 0.00, 1.00, 1.00
    bezier = ease_in,         0.55, 0.06, 0.68, 0.19
    bezier = ease_out,        0.21, 0.61, 0.35, 1.00 
    bezier = ease_in_out,     0.65, 0.04, 0.35, 1.00

    bezier = ease_in_exp,     0.95, 0.05, 0.80, 0.04
    bezier = ease_out_exp,    0.19, 1.00, 0.22, 1.00
    bezier = ease_in_out_exp, 1.00, 0.00, 0.00, 1.00

    # animation = NAME, ONOFF, SPEED, CURVE [,STYLE]

    animation = windows, 1, 3, ease_out_exp
        animation = windowsIn, 1, 3, ease_out_exp, popin 50%
        animation = windowsOut, 1, 3, ease_out_exp, popin 80%

    animation = layers, 1, 3, ease_out_exp, popin 90%

    animation = fadeOut, 1, 3, ease_out
    animation = fadeLayersOut, 1, 3, ease_out
    animation = fadeShadow, 1, 9, ease_out

    animation = border, 1, 9, ease_out

    animation = workspaces, 1, 4, ease_out_exp
}

dwindle {
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

gestures {
    workspace_swipe_cancel_ratio = 0.2
}

plugin {
    hyprbars {
        enabled = true
        bar_height = 25
        bar_blur = true
        bar_color = rgba(00000033)
        bar_padding = 10
        bar_precedence_over_border = true

        hyprbars-button = rgba(00000000), 18, , hyprctl dispatch killactive
        hyprbars-button = rgba(00000000), 18, , hyprctl dispatch fullscreen
        hyprbars-button = rgba(00000000), 18, , ~/.config/hypr/scripts/toggle_floating.sh

        icon_on_hover = true
    }

    hyprexpo {
        columns = 3
        gap_size = 10
        bg_col = rgb(000000)
    }
}
