##########################
### WINDOWS AND LAYERS ###
##########################

layerrule = animation fade, match:namespace wallpaper
layerrule = animation fade, blur on, ignore_alpha 0.1, match:namespace waybar
layerrule = blur on, ignore_alpha 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, match:namespace notifications
layerrule = no_anim on, match:namespace wayfreeze
layerrule = no_anim on, match:namespace selection
layerrule = no_anim on, match:namespace hyprpicker

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# File chooser (and probably other things)
windowrule = match:class xdg-desktop-portal-gtk, float on, size 600 400

# Waybar widgets

    # Iwgtk
    windowrule = match:class (org.twosheds.iwgtk), animation slide, float on, pin on, size 600 377, move monitor_w*0.5-300 40
    windowrule = match:class (iwgtk), float on, pin on, size 300 200, move monitor_w*0.5-150 monitor_h*0.5-100 
                                                       
    # Pwvucontrol                                      
    windowrule = match:class (com.saivert.pwvucontrol), animation slide, float on, pin on, size 900 600, move monitor_w*0.5-450 40
                                                       
    # Bluetooth                                        
    windowrule = match:class (com.ezratweaver.AdwBluetooth), match:title (Bluetooth), animation slide, float on, pin on, size 600 400, move monitor_w*0.5-300 40
    # This fixes a weird glitch that is beyond my comprehension
    windowrule = match:class (com.ezratweaver.AdwBluetooth), match:title (com.ezratweaver.AdwBluetooth), float on, pin on, size window_w-20 window_h-20, move monitor_w*0.5-(window_w-20)*0.5 monitor_h*0.5-(window_h-20)*0.5 
                                                       
    # Power menu                                       
    windowrule = match:class (yad.power), animation slide, float on, pin on, size 300 50, move monitor_w*0.5-150 40,

    # Charge limit menu
    windowrule = match:class (yad.charge), animation slide, float on, pin on, size 250 129, move 5 40,

    # Calendar
    windowrule = match:class (yad.calendar), animation slide, float on, pin on, size 338 233, move monitor_w-344 40,

# Clipse
windowrule = match:class (clipse), float on, size 520 500, move cursor_x-260 cursor_y-250

# Unipicker
windowrule = match:class (unicode-input), float on, size 600 300, move cursor_x-300 cursor_y-150

# Qalculate
windowrule = match:class (qalculate-gtk), float on, size 400 250, move cursor_x-200 cursor_y-125
