#!/usr/bin/env bash
set -euo pipefail

paths=()
for item in "$@"; do
    [[ "$item" == file://* ]] && item="${item#file://}"
    paths+=("$(realpath "$item")")
done

set-wallpaper ../../../../../${paths[0]}
